variables:
  IMG_NAME: "registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMG_TAG: "${CI_COMMIT_REF_SLUG}"
  IMG: "${IMG_NAME}:${IMG_TAG}"

build:
  image: docker:18.09
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: [ "--tls=false" ]
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t $IMG -f ./Dockerfile .
    - docker push $IMG
  only:
    - main
    - next
  tags:
    - build

deploy:
  image: alpine/helm:3.2.1
  stage: deploy
  script:
    - helm upgrade --install 
      "${CI_PROJECT_NAME}.production"
      --namespace azpays-core
      --set name="core-prod"
      --set domainName="api.azpays.net"
      --set tls.enabled="true"
      --set image.repository="$IMG_NAME"
      --set image.tag="$IMG_TAG"
      --set app.debug="$MAIN_APP_DEBUG"
      --set app.env="$MAIN_APP_ENV"
      --set app.key="$MAIN_APP_KEY"
      --set app.url="$MAIN_APP_URL"
      --set app.db.connection="$MAIN_DB_CONNECTION"
      --set app.db.database="$MAIN_DB_DATABASE"
      --set app.db.host="$MAIN_DB_HOST"
      --set app.db.port="$MAIN_DB_PORT"
      --set app.db.user="$MAIN_DB_USER"
      --set app.db.pass="$MAIN_DB_PASS"
      --create-namespace
      .ci/chart
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://api.azpays.net
  only:
    - main
  needs: ["build"]

deploy_next:
  image: alpine/helm:3.2.1
  stage: deploy
  script:
    - helm upgrade --install 
      "${CI_PROJECT_NAME}.next"
      --namespace azpays-core
      --set name="core-next"
      --set domainName="next-api.azpays.net"
      --set image.repository="${IMG_NAME}"
      --set image.tag="${IMG_TAG}"
      --set tls.enabled="true"
      --set app.debug="$NEXT_APP_DEBUG"
      --set app.env="$NEXT_APP_ENV"
      --set app.key="$NEXT_APP_KEY"
      --set app.url="$NEXT_APP_URL"
      --set app.db.connection="$NEXT_DB_CONNECTION"
      --set app.db.database="$NEXT_DB_DATABASE"
      --set app.db.host="$NEXT_DB_HOST"
      --set app.db.port="$NEXT_DB_PORT"
      --set app.db.user="$NEXT_DB_USER"
      --set app.db.pass="$NEXT_DB_PASS"
      --create-namespace
      .ci/chart
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://next-api.azpays.net
  only:
    - next
  needs: ["build"]
