name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "api.azpays.net"

tls:
  enabled: false
  issuer: le-clusterissuer
  secretName: api-azpays-net

image:
  repository: "azpays.{{ .Values.name }}-core"
  pullPolicy: Always
  tag: latest

app:
  debug: "false"
  env: local
  key: super_secure_app_key
  url: http://localhost:8080
  db:
    connection: "mysql"
    database: "name"
    host: "localhost"
    port: "3306"
    user: "doadmin"
    pass: "super_secure_db_pass"

resources: {}
tolerations: {}
